"""
Builds data/riso-map.ts, the footer map's geometry, from OpenStreetMap.

The snapshot in scripts/osm-snapshot.json was fetched 2026-09-28 from the Overpass API
(highways and railways within 230 m of Sapien Center, buildings within 60 m). Map data
(c) OpenStreetMap contributors, ODbL; the footer credits it. Re-run after a fresh fetch:
    python3 scripts/build-riso-map.py
Projection: equirectangular around the frame centre, north up, 0.40 m per viewBox unit,
so the map is to scale and the scale bar is true.
"""
import json, math, pathlib

HERE = pathlib.Path(__file__).parent
d = json.loads((HERE / "osm-snapshot.json").read_text())
W, H = 600, 420
CLAT, CLON = 30.26150, -97.71520
MPP = 0.40
KY = 111320.0
KX = 111320.0 * math.cos(math.radians(CLAT))

def P(lat, lon):
    return (round(W / 2 + (lon - CLON) * KX / MPP, 1), round(H / 2 - (lat - CLAT) * KY / MPP, 1))

def path(pts):
    return "M" + " L".join(f"{x} {y}" for x, y in pts)

KEEP = {"primary", "tertiary", "residential"}
roads, rails, building = {}, [], None
nw = []  # Northwestern Avenue polylines, for the parking bands
for e in d["elements"]:
    t, g = e.get("tags", {}), e.get("geometry", [])
    if not g:
        continue
    pts = [P(p["lat"], p["lon"]) for p in g]
    if t.get("highway") in KEEP:
        roads.setdefault(t["highway"], []).append(path(pts))
        if t.get("name") == "Northwestern Avenue":
            nw.append(pts)
    elif t.get("railway") == "rail":
        rails.append(path(pts))
    elif t.get("addr:housenumber") == "2316" and "building" in t:
        building = path(pts) + " Z"

# Parking: both kerbs of Northwestern Avenue between East 7th Street and Coronado Street,
# where the church's parking image marks it. Offset the centreline by half a road width.
seg = [p for line in nw for p in line if 118 <= p[1] <= 292]
seg.sort(key=lambda p: -p[1])
def offset(pts, dist):
    out = []
    for i, (x, y) in enumerate(pts):
        ax, ay = pts[max(i - 1, 0)]
        bx, by = pts[min(i + 1, len(pts) - 1)]
        dx, dy = bx - ax, by - ay
        n = math.hypot(dx, dy) or 1
        out.append((round(x - dy / n * dist, 1), round(y + dx / n * dist, 1)))
    return out
def trim(pts, a, b):   # keep the stretch from fraction a to b of the way along, clear of both junctions
    (x0, y0), (x1, y1) = pts[0], pts[-1]
    return [(round(x0 + (x1 - x0) * f, 1), round(y0 + (y1 - y0) * f, 1)) for f in (a, b)]
seg = trim(seg, 0.14, 0.88)
parking = [path(offset(seg, 15)), path(offset(seg, -15))]

ts = "// Generated by scripts/build-riso-map.py from OpenStreetMap (c) OpenStreetMap contributors, ODbL.\n"
ts += "// Do not edit by hand. viewBox 0 0 600 420, north up, 0.40 m per unit.\n\n"
ts += "export const risoMap = " + json.dumps(
    {"primary": roads.get("primary", []), "tertiary": roads.get("tertiary", []),
     "residential": roads.get("residential", []), "rails": rails, "building": building,
     "parking": parking, "metresPerUnit": MPP}, indent=2) + " as const;\n"
(HERE.parent / "data" / "riso-map.ts").write_text(ts)
print("ok", {k: len(v) for k, v in roads.items()}, "parking pts", len(seg))
